/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.api;

import io.alapierre.ksef.client.model.GetPaymentIdentifierReferenceNumbersResponse;
import io.alapierre.ksef.client.model.RequestPaymentIdentifierRequest;
import io.alapierre.ksef.client.model.RequestPaymentIdentifierResponse;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for InterfejsyInteraktywnePatnociApi
 */
@Ignore
public class InterfejsyInteraktywnePatnociApiTest {

    private final InterfejsyInteraktywnePatnociApi api = new InterfejsyInteraktywnePatnociApi();

    /**
     * Pobranie listy faktur dla identyfikatora płatności
     *
     * Pobranie listy faktur dla identyfikatora płatności
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getPaymentIdentifierReferenceNumbersTest() throws Exception {
        String paymentIdentifier = null;
        GetPaymentIdentifierReferenceNumbersResponse response = api.getPaymentIdentifierReferenceNumbers(paymentIdentifier);

        // TODO: test validations
    }
    /**
     * Wygenerowanie identyfikatora płatności
     *
     * Wygenerowanie identyfikatora płatności
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void requestPaymentIdentifierTest() throws Exception {
        RequestPaymentIdentifierRequest body = null;
        RequestPaymentIdentifierResponse response = api.requestPaymentIdentifier(body);

        // TODO: test validations
    }
}
