/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.api;

import io.alapierre.ksef.client.model.AuthorisationChallengeRequest;
import io.alapierre.ksef.client.model.AuthorisationChallengeResponse;
import io.alapierre.ksef.client.model.InitSessionResponse;
import io.alapierre.ksef.client.model.SessionStatusResponse;
import io.alapierre.ksef.client.model.TerminateSessionResponse;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for InterfejsyInteraktywneSesjaApi
 */
@Ignore
public class InterfejsyInteraktywneSesjaApiTest {

    private final InterfejsyInteraktywneSesjaApi api = new InterfejsyInteraktywneSesjaApi();

    /**
     * Inicjalizacja mechanizmu uwierzytelnienia i autoryzacji
     *
     * Inicjalizacja mechanizmu uwierzytelnienia i autoryzacji.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void authorisationChallengeTest() throws Exception {
        AuthorisationChallengeRequest body = null;
        AuthorisationChallengeResponse response = api.authorisationChallenge(body);

        // TODO: test validations
    }
    /**
     * Inicjalizacja sesji, wskazanie kontekstu, uwierzytelnienie i autoryzacja
     *
     * Inicjalizacja sesji interaktywnej. Podpisany dokument http://ksef.mf.gov.pl/schema/gtw/svc/online/auth/request/2021/10/01/0001/InitSessionSignedRequest
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void initSessionSignedTest() throws Exception {
        Object body = null;
        InitSessionResponse response = api.initSessionSigned(body);

        // TODO: test validations
    }
    /**
     * Inicjalizacja sesji, wskazanie kontekstu, uwierzytelnienie i autoryzacja
     *
     * Inicjalizacja sesji interaktywnej. Zaszyfrowany kluczem publicznym KSeF dokument http://ksef.mf.gov.pl/schema/gtw/svc/online/auth/request/2021/10/01/0001/InitSessionTokenRequest
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void initSessionTokenTest() throws Exception {
        Object body = null;
        InitSessionResponse response = api.initSessionToken(body);

        // TODO: test validations
    }
    /**
     * Sprawdzenie statusu aktywnej sesji interaktywnej
     *
     * Sprawdzenie statusu obecnego przetwarzania interaktywnego
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sessionStatusPlainTest() throws Exception {
        Integer pageSize = null;
        Integer pageOffset = null;
        SessionStatusResponse response = api.sessionStatusPlain(pageSize, pageOffset);

        // TODO: test validations
    }
    /**
     * Sprawdzenie statusu sesji ogólnej
     *
     * Sprawdzenie statusu przetwarzania na podstawie numeru referencyjnego
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sessionStatusReferenceNumberTest() throws Exception {
        String referenceNumber = null;
        Integer pageSize = null;
        Integer pageOffset = null;
        SessionStatusResponse response = api.sessionStatusReferenceNumber(referenceNumber, pageSize, pageOffset);

        // TODO: test validations
    }
    /**
     * Wymuszenie zamknięcia sesji
     *
     * Wymuszenie zamknięcia sesji interaktywnej
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void terminateSessionTest() throws Exception {
        TerminateSessionResponse response = api.terminateSession();

        // TODO: test validations
    }
}
