/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.api;

import io.alapierre.ksef.client.model.GenerateTokenRequest;
import io.alapierre.ksef.client.model.GenerateTokenResponse;
import io.alapierre.ksef.client.model.GrantCredentialsRequest;
import io.alapierre.ksef.client.model.RevokeCredentialsRequest;
import io.alapierre.ksef.client.model.StatusCredentialsResponse;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for InterfejsyInteraktywnePowiadczeniaApi
 */
@Ignore
public class InterfejsyInteraktywnePowiadczeniaApiTest {

    private final InterfejsyInteraktywnePowiadczeniaApi api = new InterfejsyInteraktywnePowiadczeniaApi();

    /**
     * Generowanie tokena autoryzacyjnego
     *
     * Generowanie tokena autoryzacyjnego
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void generateTokenTest() throws Exception {
        GenerateTokenRequest body = null;
        GenerateTokenResponse response = api.generateToken(body);

        // TODO: test validations
    }
    /**
     * Nadanie poświadczeń
     *
     * Nadanie poświadczeń
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void grantCredentialsTest() throws Exception {
        GrantCredentialsRequest body = null;
        StatusCredentialsResponse response = api.grantCredentials(body);

        // TODO: test validations
    }
    /**
     * Odebranie poświadczeń
     *
     * Odebranie poświadczeń
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void revokeCredentialsTest() throws Exception {
        RevokeCredentialsRequest body = null;
        StatusCredentialsResponse response = api.revokeCredentials(body);

        // TODO: test validations
    }
    /**
     * Sprawdzenie statusu poświadczeń
     *
     * Sprawdzenie statusu poświadczeń
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void statusCredentialsTest() throws Exception {
        String credentialsElementReferenceNumber = null;
        StatusCredentialsResponse response = api.statusCredentials(credentialsElementReferenceNumber);

        // TODO: test validations
    }
}
