/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.api;

import io.alapierre.ksef.client.model.QueryInvoiceAsyncInitResponse;
import io.alapierre.ksef.client.model.QueryInvoiceAsyncStatusResponse;
import io.alapierre.ksef.client.model.QueryInvoiceRequest;
import io.alapierre.ksef.client.model.QueryInvoiceSyncResponse;
import io.alapierre.ksef.client.model.QuerySyncCredentialsRequest;
import io.alapierre.ksef.client.model.QuerySyncCredentialsResponse;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for InterfejsyInteraktywneZapytaniaApi
 */
@Ignore
public class InterfejsyInteraktywneZapytaniaApiTest {

    private final InterfejsyInteraktywneZapytaniaApi api = new InterfejsyInteraktywneZapytaniaApi();

    /**
     * Zapytanie o poświadczenia
     *
     * Zapytanie o poświadczenia
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void queryCredentialsSyncTest() throws Exception {
        QuerySyncCredentialsRequest body = null;
        QuerySyncCredentialsResponse response = api.queryCredentialsSync(body);

        // TODO: test validations
    }
    /**
     * Pobranie wyników zapytania o faktury
     *
     * Pobranie wyników zapytania o faktury
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void queryInvoiceAsyncFetchTest() throws Exception {
        String queryElementReferenceNumber = null;
        String partElementReferenceNumber = null;
        Object response = api.queryInvoiceAsyncFetch(queryElementReferenceNumber, partElementReferenceNumber);

        // TODO: test validations
    }
    /**
     * Inicjalizacja zapytania o faktury
     *
     * Inicjalizacja zapytania o faktury
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void queryInvoiceAsyncInitTest() throws Exception {
        QueryInvoiceRequest body = null;
        QueryInvoiceAsyncInitResponse response = api.queryInvoiceAsyncInit(body);

        // TODO: test validations
    }
    /**
     * Sprawdzenie statusu zapytania o faktury
     *
     * Sprawdzenie statusu zapytania o faktury
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void queryInvoiceAsyncStatusTest() throws Exception {
        String queryElementReferenceNumber = null;
        QueryInvoiceAsyncStatusResponse response = api.queryInvoiceAsyncStatus(queryElementReferenceNumber);

        // TODO: test validations
    }
    /**
     * Zapytanie o faktury
     *
     * Zapytanie o faktury
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void queryInvoiceSyncTest() throws Exception {
        QueryInvoiceRequest body = null;
        Integer pageSize = null;
        Integer pageOffset = null;
        QueryInvoiceSyncResponse response = api.queryInvoiceSync(body, pageSize, pageOffset);

        // TODO: test validations
    }
}
