POST https://{{host}}.mf.gov.pl/api/online/Payment/Identifier/Request
Accept: application/json
SessionToken: {{token}}
Content-Type: application/json

{
  "ksefReferenceNumberList": [
    "{{ksef_nr1}}",
    "{{ksef_nr2}}"
  ]
}
