/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * AuthorisationChallengeRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class AuthorisationChallengeRequest {
  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  @SerializedName("contextIdentifier")
  private SubjectIdentifierByType contextIdentifier = null;

  public AuthorisationChallengeRequest timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public AuthorisationChallengeRequest contextIdentifier(SubjectIdentifierByType contextIdentifier) {
    this.contextIdentifier = contextIdentifier;
    return this;
  }

   /**
   * Get contextIdentifier
   * @return contextIdentifier
  **/
  @Schema(required = true, description = "")
  public SubjectIdentifierByType getContextIdentifier() {
    return contextIdentifier;
  }

  public void setContextIdentifier(SubjectIdentifierByType contextIdentifier) {
    this.contextIdentifier = contextIdentifier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorisationChallengeRequest authorisationChallengeRequest = (AuthorisationChallengeRequest) o;
    return Objects.equals(this.timestamp, authorisationChallengeRequest.timestamp) &&
        Objects.equals(this.contextIdentifier, authorisationChallengeRequest.contextIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, contextIdentifier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorisationChallengeRequest {\n");

    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    contextIdentifier: ").append(toIndentedString(contextIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
