/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CredentialsRoleRequestStandardBaseType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class CredentialsRoleRequestStandardBaseType {
  /**
   * Gets or Sets roleType
   */
  @JsonAdapter(RoleTypeEnum.Adapter.class)
  public enum RoleTypeEnum {
    INVOICE_READ("invoice_read"),
    INVOICE_WRITE("invoice_write"),
    PAYMENT_CONFIRMATION_WRITE("payment_confirmation_write"),
    CREDENTIALS_READ("credentials_read"),
    CREDENTIALS_MANAGE("credentials_manage"),
    SELF_INVOICING("self_invoicing"),
    TAX_REPRESENTATIVE("tax_representative"),
    ENFORCEMENT_OPERATIONS("enforcement_operations");

    private String value;

    RoleTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static RoleTypeEnum fromValue(String input) {
      for (RoleTypeEnum b : RoleTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<RoleTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RoleTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public RoleTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return RoleTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("roleType")
  private RoleTypeEnum roleType = null;

  public CredentialsRoleRequestStandardBaseType roleType(RoleTypeEnum roleType) {
    this.roleType = roleType;
    return this;
  }

   /**
   * Get roleType
   * @return roleType
  **/
  @Schema(required = true, description = "")
  public RoleTypeEnum getRoleType() {
    return roleType;
  }

  public void setRoleType(RoleTypeEnum roleType) {
    this.roleType = roleType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CredentialsRoleRequestStandardBaseType credentialsRoleRequestStandardBaseType = (CredentialsRoleRequestStandardBaseType) o;
    return Objects.equals(this.roleType, credentialsRoleRequestStandardBaseType.roleType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roleType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CredentialsRoleRequestStandardBaseType {\n");

    sb.append("    roleType: ").append(toIndentedString(roleType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
