/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CredentialsIdentifierResponseIndividualNipType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class CredentialsIdentifierResponseIndividualNipType extends CredentialsIdentifierResponseType {
  @SerializedName("identifier")
  private String credentialsIdentifierResponseIndividualNipTypeIdentifier = null;

  public CredentialsIdentifierResponseIndividualNipType credentialsIdentifierResponseIndividualNipTypeIdentifier(String credentialsIdentifierResponseIndividualNipTypeIdentifier) {
    this.credentialsIdentifierResponseIndividualNipTypeIdentifier = credentialsIdentifierResponseIndividualNipTypeIdentifier;
    return this;
  }

   /**
   * Get credentialsIdentifierResponseIndividualNipTypeIdentifier
   * @return credentialsIdentifierResponseIndividualNipTypeIdentifier
  **/
  @Schema(required = true, description = "")
  public String getCredentialsIdentifierResponseIndividualNipTypeIdentifier() {
    return credentialsIdentifierResponseIndividualNipTypeIdentifier;
  }

  public void setCredentialsIdentifierResponseIndividualNipTypeIdentifier(String credentialsIdentifierResponseIndividualNipTypeIdentifier) {
    this.credentialsIdentifierResponseIndividualNipTypeIdentifier = credentialsIdentifierResponseIndividualNipTypeIdentifier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CredentialsIdentifierResponseIndividualNipType credentialsIdentifierResponseIndividualNipType = (CredentialsIdentifierResponseIndividualNipType) o;
    return Objects.equals(this.credentialsIdentifierResponseIndividualNipTypeIdentifier, credentialsIdentifierResponseIndividualNipType.credentialsIdentifierResponseIndividualNipTypeIdentifier) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(credentialsIdentifierResponseIndividualNipTypeIdentifier, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CredentialsIdentifierResponseIndividualNipType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    credentialsIdentifierResponseIndividualNipTypeIdentifier: ").append(toIndentedString(credentialsIdentifierResponseIndividualNipTypeIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
