/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * CredentialsType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class CredentialsType {
  @SerializedName("identifier")
  private CredentialsIdentifierResponseType identifier = null;

  @SerializedName("credentialsRoleList")
  private List<CredentialsRoleResponseType> credentialsRoleList = new ArrayList<CredentialsRoleResponseType>();

  public CredentialsType identifier(CredentialsIdentifierResponseType identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * Get identifier
   * @return identifier
  **/
  @Schema(required = true, description = "")
  public CredentialsIdentifierResponseType getIdentifier() {
    return identifier;
  }

  public void setIdentifier(CredentialsIdentifierResponseType identifier) {
    this.identifier = identifier;
  }

  public CredentialsType credentialsRoleList(List<CredentialsRoleResponseType> credentialsRoleList) {
    this.credentialsRoleList = credentialsRoleList;
    return this;
  }

  public CredentialsType addCredentialsRoleListItem(CredentialsRoleResponseType credentialsRoleListItem) {
    this.credentialsRoleList.add(credentialsRoleListItem);
    return this;
  }

   /**
   * Get credentialsRoleList
   * @return credentialsRoleList
  **/
  @Schema(required = true, description = "")
  public List<CredentialsRoleResponseType> getCredentialsRoleList() {
    return credentialsRoleList;
  }

  public void setCredentialsRoleList(List<CredentialsRoleResponseType> credentialsRoleList) {
    this.credentialsRoleList = credentialsRoleList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CredentialsType credentialsType = (CredentialsType) o;
    return Objects.equals(this.identifier, credentialsType.identifier) &&
        Objects.equals(this.credentialsRoleList, credentialsType.credentialsRoleList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, credentialsRoleList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CredentialsType {\n");

    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    credentialsRoleList: ").append(toIndentedString(credentialsRoleList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
