/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ExceptionDetailType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class ExceptionDetailType {
  @SerializedName("exceptionCode")
  private Integer exceptionCode = null;

  @SerializedName("exceptionDescription")
  private String exceptionDescription = null;

  public ExceptionDetailType exceptionCode(Integer exceptionCode) {
    this.exceptionCode = exceptionCode;
    return this;
  }

   /**
   * Get exceptionCode
   * minimum: 0
   * @return exceptionCode
  **/
  @Schema(required = true, description = "")
  public Integer getExceptionCode() {
    return exceptionCode;
  }

  public void setExceptionCode(Integer exceptionCode) {
    this.exceptionCode = exceptionCode;
  }

  public ExceptionDetailType exceptionDescription(String exceptionDescription) {
    this.exceptionDescription = exceptionDescription;
    return this;
  }

   /**
   * Get exceptionDescription
   * @return exceptionDescription
  **/
  @Schema(required = true, description = "")
  public String getExceptionDescription() {
    return exceptionDescription;
  }

  public void setExceptionDescription(String exceptionDescription) {
    this.exceptionDescription = exceptionDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExceptionDetailType exceptionDetailType = (ExceptionDetailType) o;
    return Objects.equals(this.exceptionCode, exceptionDetailType.exceptionCode) &&
        Objects.equals(this.exceptionDescription, exceptionDetailType.exceptionDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exceptionCode, exceptionDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExceptionDetailType {\n");

    sb.append("    exceptionCode: ").append(toIndentedString(exceptionCode)).append("\n");
    sb.append("    exceptionDescription: ").append(toIndentedString(exceptionDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
