/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * ExceptionType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class ExceptionType {
  @SerializedName("serviceCtx")
  private String serviceCtx = null;

  @SerializedName("serviceCode")
  private String serviceCode = null;

  @SerializedName("serviceName")
  private String serviceName = null;

  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  @SerializedName("referenceNumber")
  private String referenceNumber = null;

  @SerializedName("exceptionDetailList")
  private List<ExceptionDetailType> exceptionDetailList = new ArrayList<ExceptionDetailType>();

  public ExceptionType serviceCtx(String serviceCtx) {
    this.serviceCtx = serviceCtx;
    return this;
  }

   /**
   * Get serviceCtx
   * @return serviceCtx
  **/
  @Schema(required = true, description = "")
  public String getServiceCtx() {
    return serviceCtx;
  }

  public void setServiceCtx(String serviceCtx) {
    this.serviceCtx = serviceCtx;
  }

  public ExceptionType serviceCode(String serviceCode) {
    this.serviceCode = serviceCode;
    return this;
  }

   /**
   * Get serviceCode
   * @return serviceCode
  **/
  @Schema(required = true, description = "")
  public String getServiceCode() {
    return serviceCode;
  }

  public void setServiceCode(String serviceCode) {
    this.serviceCode = serviceCode;
  }

  public ExceptionType serviceName(String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

   /**
   * Get serviceName
   * @return serviceName
  **/
  @Schema(required = true, description = "")
  public String getServiceName() {
    return serviceName;
  }

  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }

  public ExceptionType timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public ExceptionType referenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

   /**
   * Get referenceNumber
   * @return referenceNumber
  **/
  @Schema(description = "")
  public String getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
  }

  public ExceptionType exceptionDetailList(List<ExceptionDetailType> exceptionDetailList) {
    this.exceptionDetailList = exceptionDetailList;
    return this;
  }

  public ExceptionType addExceptionDetailListItem(ExceptionDetailType exceptionDetailListItem) {
    this.exceptionDetailList.add(exceptionDetailListItem);
    return this;
  }

   /**
   * Get exceptionDetailList
   * @return exceptionDetailList
  **/
  @Schema(required = true, description = "")
  public List<ExceptionDetailType> getExceptionDetailList() {
    return exceptionDetailList;
  }

  public void setExceptionDetailList(List<ExceptionDetailType> exceptionDetailList) {
    this.exceptionDetailList = exceptionDetailList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExceptionType exceptionType = (ExceptionType) o;
    return Objects.equals(this.serviceCtx, exceptionType.serviceCtx) &&
        Objects.equals(this.serviceCode, exceptionType.serviceCode) &&
        Objects.equals(this.serviceName, exceptionType.serviceName) &&
        Objects.equals(this.timestamp, exceptionType.timestamp) &&
        Objects.equals(this.referenceNumber, exceptionType.referenceNumber) &&
        Objects.equals(this.exceptionDetailList, exceptionType.exceptionDetailList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceCtx, serviceCode, serviceName, timestamp, referenceNumber, exceptionDetailList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExceptionType {\n");

    sb.append("    serviceCtx: ").append(toIndentedString(serviceCtx)).append("\n");
    sb.append("    serviceCode: ").append(toIndentedString(serviceCode)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("    exceptionDetailList: ").append(toIndentedString(exceptionDetailList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
