/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * FileUnlimitedHashType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class FileUnlimitedHashType {
  @SerializedName("hashSHA")
  private HashSHAType hashSHA = null;

  @SerializedName("fileSize")
  private Integer fileSize = null;

  public FileUnlimitedHashType hashSHA(HashSHAType hashSHA) {
    this.hashSHA = hashSHA;
    return this;
  }

   /**
   * Get hashSHA
   * @return hashSHA
  **/
  @Schema(required = true, description = "")
  public HashSHAType getHashSHA() {
    return hashSHA;
  }

  public void setHashSHA(HashSHAType hashSHA) {
    this.hashSHA = hashSHA;
  }

  public FileUnlimitedHashType fileSize(Integer fileSize) {
    this.fileSize = fileSize;
    return this;
  }

   /**
   * Get fileSize
   * minimum: 0
   * @return fileSize
  **/
  @Schema(required = true, description = "")
  public Integer getFileSize() {
    return fileSize;
  }

  public void setFileSize(Integer fileSize) {
    this.fileSize = fileSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileUnlimitedHashType fileUnlimitedHashType = (FileUnlimitedHashType) o;
    return Objects.equals(this.hashSHA, fileUnlimitedHashType.hashSHA) &&
        Objects.equals(this.fileSize, fileUnlimitedHashType.fileSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashSHA, fileSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileUnlimitedHashType {\n");

    sb.append("    hashSHA: ").append(toIndentedString(hashSHA)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
