/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * GenerateTokenRequestType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class GenerateTokenRequestType {
  @SerializedName("description")
  private String description = null;

  @SerializedName("credentialsRoleList")
  private List<CredentialsRoleRequestTokenType> credentialsRoleList = new ArrayList<CredentialsRoleRequestTokenType>();

  public GenerateTokenRequestType description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public GenerateTokenRequestType credentialsRoleList(List<CredentialsRoleRequestTokenType> credentialsRoleList) {
    this.credentialsRoleList = credentialsRoleList;
    return this;
  }

  public GenerateTokenRequestType addCredentialsRoleListItem(CredentialsRoleRequestTokenType credentialsRoleListItem) {
    this.credentialsRoleList.add(credentialsRoleListItem);
    return this;
  }

   /**
   * Get credentialsRoleList
   * @return credentialsRoleList
  **/
  @Schema(required = true, description = "")
  public List<CredentialsRoleRequestTokenType> getCredentialsRoleList() {
    return credentialsRoleList;
  }

  public void setCredentialsRoleList(List<CredentialsRoleRequestTokenType> credentialsRoleList) {
    this.credentialsRoleList = credentialsRoleList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerateTokenRequestType generateTokenRequestType = (GenerateTokenRequestType) o;
    return Objects.equals(this.description, generateTokenRequestType.description) &&
        Objects.equals(this.credentialsRoleList, generateTokenRequestType.credentialsRoleList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, credentialsRoleList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerateTokenRequestType {\n");

    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    credentialsRoleList: ").append(toIndentedString(credentialsRoleList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
