/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;

/**
 * InvoicePayloadEncryptedType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class InvoicePayloadEncryptedType extends InvoicePayloadType {
  @SerializedName("encryptedInvoiceHash")
  private File2MBHashType encryptedInvoiceHash = null;

  @SerializedName("encryptedInvoiceBody")
  private File encryptedInvoiceBody = null;

  public InvoicePayloadEncryptedType encryptedInvoiceHash(File2MBHashType encryptedInvoiceHash) {
    this.encryptedInvoiceHash = encryptedInvoiceHash;
    return this;
  }

   /**
   * Get encryptedInvoiceHash
   * @return encryptedInvoiceHash
  **/
  @Schema(required = true, description = "")
  public File2MBHashType getEncryptedInvoiceHash() {
    return encryptedInvoiceHash;
  }

  public void setEncryptedInvoiceHash(File2MBHashType encryptedInvoiceHash) {
    this.encryptedInvoiceHash = encryptedInvoiceHash;
  }

  public InvoicePayloadEncryptedType encryptedInvoiceBody(File encryptedInvoiceBody) {
    this.encryptedInvoiceBody = encryptedInvoiceBody;
    return this;
  }

   /**
   * Get encryptedInvoiceBody
   * @return encryptedInvoiceBody
  **/
  @Schema(required = true, description = "")
  public File getEncryptedInvoiceBody() {
    return encryptedInvoiceBody;
  }

  public void setEncryptedInvoiceBody(File encryptedInvoiceBody) {
    this.encryptedInvoiceBody = encryptedInvoiceBody;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoicePayloadEncryptedType invoicePayloadEncryptedType = (InvoicePayloadEncryptedType) o;
    return Objects.equals(this.encryptedInvoiceHash, invoicePayloadEncryptedType.encryptedInvoiceHash) &&
        Objects.equals(this.encryptedInvoiceBody, invoicePayloadEncryptedType.encryptedInvoiceBody) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(encryptedInvoiceHash, Objects.hashCode(encryptedInvoiceBody), super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoicePayloadEncryptedType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    encryptedInvoiceHash: ").append(toIndentedString(encryptedInvoiceHash)).append("\n");
    sb.append("    encryptedInvoiceBody: ").append(toIndentedString(encryptedInvoiceBody)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
