/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;

/**
 * InvoicePayloadPlainType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class InvoicePayloadPlainType extends InvoicePayloadType {
  @SerializedName("invoiceBody")
  private File invoiceBody = null;

  public InvoicePayloadPlainType invoiceBody(File invoiceBody) {
    this.invoiceBody = invoiceBody;
    return this;
  }

   /**
   * Get invoiceBody
   * @return invoiceBody
  **/
  @Schema(required = true, description = "")
  public File getInvoiceBody() {
    return invoiceBody;
  }

  public void setInvoiceBody(File invoiceBody) {
    this.invoiceBody = invoiceBody;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoicePayloadPlainType invoicePayloadPlainType = (InvoicePayloadPlainType) o;
    return Objects.equals(this.invoiceBody, invoicePayloadPlainType.invoiceBody) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(invoiceBody), super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoicePayloadPlainType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    invoiceBody: ").append(toIndentedString(invoiceBody)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
