/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * QueryInvoiceSyncResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class QueryInvoiceSyncResponse {
  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  @SerializedName("referenceNumber")
  private String referenceNumber = null;

  @SerializedName("numberOfElements")
  private Long numberOfElements = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  @SerializedName("pageOffset")
  private Integer pageOffset = null;

  @SerializedName("invoiceHeaderList")
  private List<InvoiceHeaderType> invoiceHeaderList = new ArrayList<InvoiceHeaderType>();

  public QueryInvoiceSyncResponse timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public QueryInvoiceSyncResponse referenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

   /**
   * Get referenceNumber
   * @return referenceNumber
  **/
  @Schema(required = true, description = "")
  public String getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
  }

  public QueryInvoiceSyncResponse numberOfElements(Long numberOfElements) {
    this.numberOfElements = numberOfElements;
    return this;
  }

   /**
   * Get numberOfElements
   * minimum: 0
   * @return numberOfElements
  **/
  @Schema(required = true, description = "")
  public Long getNumberOfElements() {
    return numberOfElements;
  }

  public void setNumberOfElements(Long numberOfElements) {
    this.numberOfElements = numberOfElements;
  }

  public QueryInvoiceSyncResponse pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * minimum: 0
   * maximum: 100
   * @return pageSize
  **/
  @Schema(required = true, description = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public QueryInvoiceSyncResponse pageOffset(Integer pageOffset) {
    this.pageOffset = pageOffset;
    return this;
  }

   /**
   * Get pageOffset
   * minimum: 0
   * maximum: 100
   * @return pageOffset
  **/
  @Schema(required = true, description = "")
  public Integer getPageOffset() {
    return pageOffset;
  }

  public void setPageOffset(Integer pageOffset) {
    this.pageOffset = pageOffset;
  }

  public QueryInvoiceSyncResponse invoiceHeaderList(List<InvoiceHeaderType> invoiceHeaderList) {
    this.invoiceHeaderList = invoiceHeaderList;
    return this;
  }

  public QueryInvoiceSyncResponse addInvoiceHeaderListItem(InvoiceHeaderType invoiceHeaderListItem) {
    this.invoiceHeaderList.add(invoiceHeaderListItem);
    return this;
  }

   /**
   * Get invoiceHeaderList
   * @return invoiceHeaderList
  **/
  @Schema(required = true, description = "")
  public List<InvoiceHeaderType> getInvoiceHeaderList() {
    return invoiceHeaderList;
  }

  public void setInvoiceHeaderList(List<InvoiceHeaderType> invoiceHeaderList) {
    this.invoiceHeaderList = invoiceHeaderList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryInvoiceSyncResponse queryInvoiceSyncResponse = (QueryInvoiceSyncResponse) o;
    return Objects.equals(this.timestamp, queryInvoiceSyncResponse.timestamp) &&
        Objects.equals(this.referenceNumber, queryInvoiceSyncResponse.referenceNumber) &&
        Objects.equals(this.numberOfElements, queryInvoiceSyncResponse.numberOfElements) &&
        Objects.equals(this.pageSize, queryInvoiceSyncResponse.pageSize) &&
        Objects.equals(this.pageOffset, queryInvoiceSyncResponse.pageOffset) &&
        Objects.equals(this.invoiceHeaderList, queryInvoiceSyncResponse.invoiceHeaderList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, referenceNumber, numberOfElements, pageSize, pageOffset, invoiceHeaderList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryInvoiceSyncResponse {\n");

    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("    numberOfElements: ").append(toIndentedString(numberOfElements)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    pageOffset: ").append(toIndentedString(pageOffset)).append("\n");
    sb.append("    invoiceHeaderList: ").append(toIndentedString(invoiceHeaderList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
