/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * QueryCriteriaInvoiceDetailType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class QueryCriteriaInvoiceDetailType extends QueryCriteriaInvoiceType {
  @SerializedName("invoiceNumber")
  private String invoiceNumber = null;

  @SerializedName("ksefReferenceNumber")
  private String ksefReferenceNumber = null;

  @SerializedName("invoicingDateFrom")
  private OffsetDateTime invoicingDateFrom = null;

  @SerializedName("invoicingDateTo")
  private OffsetDateTime invoicingDateTo = null;

  @SerializedName("subjectBy")
  private SubjectByType subjectBy = null;

  @SerializedName("subjectTo")
  private SubjectToType subjectTo = null;

  public QueryCriteriaInvoiceDetailType invoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
    return this;
  }

   /**
   * Get invoiceNumber
   * @return invoiceNumber
  **/
  @Schema(description = "")
  public String getInvoiceNumber() {
    return invoiceNumber;
  }

  public void setInvoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
  }

  public QueryCriteriaInvoiceDetailType ksefReferenceNumber(String ksefReferenceNumber) {
    this.ksefReferenceNumber = ksefReferenceNumber;
    return this;
  }

   /**
   * Get ksefReferenceNumber
   * @return ksefReferenceNumber
  **/
  @Schema(description = "")
  public String getKsefReferenceNumber() {
    return ksefReferenceNumber;
  }

  public void setKsefReferenceNumber(String ksefReferenceNumber) {
    this.ksefReferenceNumber = ksefReferenceNumber;
  }

  public QueryCriteriaInvoiceDetailType invoicingDateFrom(OffsetDateTime invoicingDateFrom) {
    this.invoicingDateFrom = invoicingDateFrom;
    return this;
  }

   /**
   * Get invoicingDateFrom
   * @return invoicingDateFrom
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getInvoicingDateFrom() {
    return invoicingDateFrom;
  }

  public void setInvoicingDateFrom(OffsetDateTime invoicingDateFrom) {
    this.invoicingDateFrom = invoicingDateFrom;
  }

  public QueryCriteriaInvoiceDetailType invoicingDateTo(OffsetDateTime invoicingDateTo) {
    this.invoicingDateTo = invoicingDateTo;
    return this;
  }

   /**
   * Get invoicingDateTo
   * @return invoicingDateTo
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getInvoicingDateTo() {
    return invoicingDateTo;
  }

  public void setInvoicingDateTo(OffsetDateTime invoicingDateTo) {
    this.invoicingDateTo = invoicingDateTo;
  }

  public QueryCriteriaInvoiceDetailType subjectBy(SubjectByType subjectBy) {
    this.subjectBy = subjectBy;
    return this;
  }

   /**
   * Get subjectBy
   * @return subjectBy
  **/
  @Schema(description = "")
  public SubjectByType getSubjectBy() {
    return subjectBy;
  }

  public void setSubjectBy(SubjectByType subjectBy) {
    this.subjectBy = subjectBy;
  }

  public QueryCriteriaInvoiceDetailType subjectTo(SubjectToType subjectTo) {
    this.subjectTo = subjectTo;
    return this;
  }

   /**
   * Get subjectTo
   * @return subjectTo
  **/
  @Schema(description = "")
  public SubjectToType getSubjectTo() {
    return subjectTo;
  }

  public void setSubjectTo(SubjectToType subjectTo) {
    this.subjectTo = subjectTo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryCriteriaInvoiceDetailType queryCriteriaInvoiceDetailType = (QueryCriteriaInvoiceDetailType) o;
    return Objects.equals(this.invoiceNumber, queryCriteriaInvoiceDetailType.invoiceNumber) &&
        Objects.equals(this.ksefReferenceNumber, queryCriteriaInvoiceDetailType.ksefReferenceNumber) &&
        Objects.equals(this.invoicingDateFrom, queryCriteriaInvoiceDetailType.invoicingDateFrom) &&
        Objects.equals(this.invoicingDateTo, queryCriteriaInvoiceDetailType.invoicingDateTo) &&
        Objects.equals(this.subjectBy, queryCriteriaInvoiceDetailType.subjectBy) &&
        Objects.equals(this.subjectTo, queryCriteriaInvoiceDetailType.subjectTo) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invoiceNumber, ksefReferenceNumber, invoicingDateFrom, invoicingDateTo, subjectBy, subjectTo, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryCriteriaInvoiceDetailType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    invoiceNumber: ").append(toIndentedString(invoiceNumber)).append("\n");
    sb.append("    ksefReferenceNumber: ").append(toIndentedString(ksefReferenceNumber)).append("\n");
    sb.append("    invoicingDateFrom: ").append(toIndentedString(invoicingDateFrom)).append("\n");
    sb.append("    invoicingDateTo: ").append(toIndentedString(invoicingDateTo)).append("\n");
    sb.append("    subjectBy: ").append(toIndentedString(subjectBy)).append("\n");
    sb.append("    subjectTo: ").append(toIndentedString(subjectTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
