/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * QueryCriteriaCredentialsType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")

public class QueryCriteriaCredentialsType {
  /**
   * Gets or Sets structureType
   */
  @JsonAdapter(StructureTypeEnum.Adapter.class)
  public enum StructureTypeEnum {
    TREE("tree"),
    PLAIN("plain");

    private String value;

    StructureTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StructureTypeEnum fromValue(String input) {
      for (StructureTypeEnum b : StructureTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<StructureTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StructureTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public StructureTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return StructureTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("structureType")
  private StructureTypeEnum structureType = null;

  public QueryCriteriaCredentialsType() {
    this.structureType = StructureTypeEnum.valueOf(this.getClass().getSimpleName());
  }
  public QueryCriteriaCredentialsType structureType(StructureTypeEnum structureType) {
    this.structureType = structureType;
    return this;
  }

   /**
   * Get structureType
   * @return structureType
  **/
  @Schema(required = true, description = "")
  public StructureTypeEnum getStructureType() {
    return structureType;
  }

  public void setStructureType(StructureTypeEnum structureType) {
    this.structureType = structureType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryCriteriaCredentialsType queryCriteriaCredentialsType = (QueryCriteriaCredentialsType) o;
    return Objects.equals(this.structureType, queryCriteriaCredentialsType.structureType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(structureType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryCriteriaCredentialsType {\n");

    sb.append("    structureType: ").append(toIndentedString(structureType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
