/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * RequestPaymentIdentifierResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class RequestPaymentIdentifierResponse {
  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  @SerializedName("referenceNumber")
  private String referenceNumber = null;

  @SerializedName("paymentIdentifier")
  private String paymentIdentifier = null;

  public RequestPaymentIdentifierResponse timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public RequestPaymentIdentifierResponse referenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

   /**
   * Get referenceNumber
   * @return referenceNumber
  **/
  @Schema(required = true, description = "")
  public String getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
  }

  public RequestPaymentIdentifierResponse paymentIdentifier(String paymentIdentifier) {
    this.paymentIdentifier = paymentIdentifier;
    return this;
  }

   /**
   * Get paymentIdentifier
   * @return paymentIdentifier
  **/
  @Schema(required = true, description = "")
  public String getPaymentIdentifier() {
    return paymentIdentifier;
  }

  public void setPaymentIdentifier(String paymentIdentifier) {
    this.paymentIdentifier = paymentIdentifier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestPaymentIdentifierResponse requestPaymentIdentifierResponse = (RequestPaymentIdentifierResponse) o;
    return Objects.equals(this.timestamp, requestPaymentIdentifierResponse.timestamp) &&
        Objects.equals(this.referenceNumber, requestPaymentIdentifierResponse.referenceNumber) &&
        Objects.equals(this.paymentIdentifier, requestPaymentIdentifierResponse.paymentIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, referenceNumber, paymentIdentifier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestPaymentIdentifierResponse {\n");

    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("    paymentIdentifier: ").append(toIndentedString(paymentIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
