/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * SendInvoiceRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class SendInvoiceRequest {
  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  @SerializedName("invoiceHash")
  private File1MBHashType invoiceHash = null;

  @SerializedName("invoicePayload")
  private InvoicePayloadType invoicePayload = null;

  public SendInvoiceRequest timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public SendInvoiceRequest invoiceHash(File1MBHashType invoiceHash) {
    this.invoiceHash = invoiceHash;
    return this;
  }

   /**
   * Get invoiceHash
   * @return invoiceHash
  **/
  @Schema(required = true, description = "")
  public File1MBHashType getInvoiceHash() {
    return invoiceHash;
  }

  public void setInvoiceHash(File1MBHashType invoiceHash) {
    this.invoiceHash = invoiceHash;
  }

  public SendInvoiceRequest invoicePayload(InvoicePayloadType invoicePayload) {
    this.invoicePayload = invoicePayload;
    return this;
  }

   /**
   * Get invoicePayload
   * @return invoicePayload
  **/
  @Schema(required = true, description = "")
  public InvoicePayloadType getInvoicePayload() {
    return invoicePayload;
  }

  public void setInvoicePayload(InvoicePayloadType invoicePayload) {
    this.invoicePayload = invoicePayload;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendInvoiceRequest sendInvoiceRequest = (SendInvoiceRequest) o;
    return Objects.equals(this.timestamp, sendInvoiceRequest.timestamp) &&
        Objects.equals(this.invoiceHash, sendInvoiceRequest.invoiceHash) &&
        Objects.equals(this.invoicePayload, sendInvoiceRequest.invoicePayload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, invoiceHash, invoicePayload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendInvoiceRequest {\n");

    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    invoiceHash: ").append(toIndentedString(invoiceHash)).append("\n");
    sb.append("    invoicePayload: ").append(toIndentedString(invoicePayload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
