/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * SessionStatusResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class SessionStatusResponse {
  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  @SerializedName("referenceNumber")
  private String referenceNumber = null;

  @SerializedName("numberOfElements")
  private Long numberOfElements = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  @SerializedName("pageOffset")
  private Integer pageOffset = null;

  @SerializedName("processingCode")
  private Integer processingCode = null;

  @SerializedName("processingDescription")
  private String processingDescription = null;

  @SerializedName("invoiceStatusList")
  private List<SessionInvoiceStatusType> invoiceStatusList = new ArrayList<SessionInvoiceStatusType>();

  public SessionStatusResponse timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public SessionStatusResponse referenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

   /**
   * Get referenceNumber
   * @return referenceNumber
  **/
  @Schema(required = true, description = "")
  public String getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
  }

  public SessionStatusResponse numberOfElements(Long numberOfElements) {
    this.numberOfElements = numberOfElements;
    return this;
  }

   /**
   * Get numberOfElements
   * minimum: 0
   * @return numberOfElements
  **/
  @Schema(required = true, description = "")
  public Long getNumberOfElements() {
    return numberOfElements;
  }

  public void setNumberOfElements(Long numberOfElements) {
    this.numberOfElements = numberOfElements;
  }

  public SessionStatusResponse pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * minimum: 0
   * maximum: 100
   * @return pageSize
  **/
  @Schema(required = true, description = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public SessionStatusResponse pageOffset(Integer pageOffset) {
    this.pageOffset = pageOffset;
    return this;
  }

   /**
   * Get pageOffset
   * minimum: 0
   * maximum: 100
   * @return pageOffset
  **/
  @Schema(required = true, description = "")
  public Integer getPageOffset() {
    return pageOffset;
  }

  public void setPageOffset(Integer pageOffset) {
    this.pageOffset = pageOffset;
  }

  public SessionStatusResponse processingCode(Integer processingCode) {
    this.processingCode = processingCode;
    return this;
  }

   /**
   * Get processingCode
   * minimum: 100
   * maximum: 999
   * @return processingCode
  **/
  @Schema(required = true, description = "")
  public Integer getProcessingCode() {
    return processingCode;
  }

  public void setProcessingCode(Integer processingCode) {
    this.processingCode = processingCode;
  }

  public SessionStatusResponse processingDescription(String processingDescription) {
    this.processingDescription = processingDescription;
    return this;
  }

   /**
   * Get processingDescription
   * @return processingDescription
  **/
  @Schema(required = true, description = "")
  public String getProcessingDescription() {
    return processingDescription;
  }

  public void setProcessingDescription(String processingDescription) {
    this.processingDescription = processingDescription;
  }

  public SessionStatusResponse invoiceStatusList(List<SessionInvoiceStatusType> invoiceStatusList) {
    this.invoiceStatusList = invoiceStatusList;
    return this;
  }

  public SessionStatusResponse addInvoiceStatusListItem(SessionInvoiceStatusType invoiceStatusListItem) {
    this.invoiceStatusList.add(invoiceStatusListItem);
    return this;
  }

   /**
   * Get invoiceStatusList
   * @return invoiceStatusList
  **/
  @Schema(required = true, description = "")
  public List<SessionInvoiceStatusType> getInvoiceStatusList() {
    return invoiceStatusList;
  }

  public void setInvoiceStatusList(List<SessionInvoiceStatusType> invoiceStatusList) {
    this.invoiceStatusList = invoiceStatusList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionStatusResponse sessionStatusResponse = (SessionStatusResponse) o;
    return Objects.equals(this.timestamp, sessionStatusResponse.timestamp) &&
        Objects.equals(this.referenceNumber, sessionStatusResponse.referenceNumber) &&
        Objects.equals(this.numberOfElements, sessionStatusResponse.numberOfElements) &&
        Objects.equals(this.pageSize, sessionStatusResponse.pageSize) &&
        Objects.equals(this.pageOffset, sessionStatusResponse.pageOffset) &&
        Objects.equals(this.processingCode, sessionStatusResponse.processingCode) &&
        Objects.equals(this.processingDescription, sessionStatusResponse.processingDescription) &&
        Objects.equals(this.invoiceStatusList, sessionStatusResponse.invoiceStatusList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, referenceNumber, numberOfElements, pageSize, pageOffset, processingCode, processingDescription, invoiceStatusList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionStatusResponse {\n");

    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("    numberOfElements: ").append(toIndentedString(numberOfElements)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    pageOffset: ").append(toIndentedString(pageOffset)).append("\n");
    sb.append("    processingCode: ").append(toIndentedString(processingCode)).append("\n");
    sb.append("    processingDescription: ").append(toIndentedString(processingDescription)).append("\n");
    sb.append("    invoiceStatusList: ").append(toIndentedString(invoiceStatusList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
