/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SubjectToType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class SubjectToType {
  @SerializedName("issuedToIdentifier")
  private SubjectIdentifierToType issuedToIdentifier = null;

  @SerializedName("issuedToName")
  private SubjectNameType issuedToName = null;

  public SubjectToType issuedToIdentifier(SubjectIdentifierToType issuedToIdentifier) {
    this.issuedToIdentifier = issuedToIdentifier;
    return this;
  }

   /**
   * Get issuedToIdentifier
   * @return issuedToIdentifier
  **/
  @Schema(required = true, description = "")
  public SubjectIdentifierToType getIssuedToIdentifier() {
    return issuedToIdentifier;
  }

  public void setIssuedToIdentifier(SubjectIdentifierToType issuedToIdentifier) {
    this.issuedToIdentifier = issuedToIdentifier;
  }

  public SubjectToType issuedToName(SubjectNameType issuedToName) {
    this.issuedToName = issuedToName;
    return this;
  }

   /**
   * Get issuedToName
   * @return issuedToName
  **/
  @Schema(description = "")
  public SubjectNameType getIssuedToName() {
    return issuedToName;
  }

  public void setIssuedToName(SubjectNameType issuedToName) {
    this.issuedToName = issuedToName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubjectToType subjectToType = (SubjectToType) o;
    return Objects.equals(this.issuedToIdentifier, subjectToType.issuedToIdentifier) &&
        Objects.equals(this.issuedToName, subjectToType.issuedToName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuedToIdentifier, issuedToName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubjectToType {\n");

    sb.append("    issuedToIdentifier: ").append(toIndentedString(issuedToIdentifier)).append("\n");
    sb.append("    issuedToName: ").append(toIndentedString(issuedToName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
