/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SubjectOtherType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class SubjectOtherType {
  @SerializedName("issuedToIdentifier")
  private SubjectIdentifierToType issuedToIdentifier = null;

  @SerializedName("issuedToName")
  private SubjectNameType issuedToName = null;

  /**
   * Gets or Sets subjectOtherType
   */
  @JsonAdapter(SubjectOtherTypeEnum.Adapter.class)
  public enum SubjectOtherTypeEnum {
    FACTOR("factor"),
    RECIPIENT("recipient"),
    ORIGINAL_SUBJECT("original_subject"),
    ADDITIONAL_PURCHASER("additional_purchaser"),
    INVOICE_ISSUER("invoice_issuer"),
    PAYER("payer"),
    OTHER("other");

    private String value;

    SubjectOtherTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static SubjectOtherTypeEnum fromValue(String input) {
      for (SubjectOtherTypeEnum b : SubjectOtherTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<SubjectOtherTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SubjectOtherTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public SubjectOtherTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return SubjectOtherTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("subjectOtherType")
  private SubjectOtherTypeEnum subjectOtherType = null;

  public SubjectOtherType issuedToIdentifier(SubjectIdentifierToType issuedToIdentifier) {
    this.issuedToIdentifier = issuedToIdentifier;
    return this;
  }

   /**
   * Get issuedToIdentifier
   * @return issuedToIdentifier
  **/
  @Schema(required = true, description = "")
  public SubjectIdentifierToType getIssuedToIdentifier() {
    return issuedToIdentifier;
  }

  public void setIssuedToIdentifier(SubjectIdentifierToType issuedToIdentifier) {
    this.issuedToIdentifier = issuedToIdentifier;
  }

  public SubjectOtherType issuedToName(SubjectNameType issuedToName) {
    this.issuedToName = issuedToName;
    return this;
  }

   /**
   * Get issuedToName
   * @return issuedToName
  **/
  @Schema(description = "")
  public SubjectNameType getIssuedToName() {
    return issuedToName;
  }

  public void setIssuedToName(SubjectNameType issuedToName) {
    this.issuedToName = issuedToName;
  }

  public SubjectOtherType subjectOtherType(SubjectOtherTypeEnum subjectOtherType) {
    this.subjectOtherType = subjectOtherType;
    return this;
  }

   /**
   * Get subjectOtherType
   * @return subjectOtherType
  **/
  @Schema(required = true, description = "")
  public SubjectOtherTypeEnum getSubjectOtherType() {
    return subjectOtherType;
  }

  public void setSubjectOtherType(SubjectOtherTypeEnum subjectOtherType) {
    this.subjectOtherType = subjectOtherType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubjectOtherType subjectOtherType = (SubjectOtherType) o;
    return Objects.equals(this.issuedToIdentifier, subjectOtherType.issuedToIdentifier) &&
        Objects.equals(this.issuedToName, subjectOtherType.issuedToName) &&
        Objects.equals(this.subjectOtherType, subjectOtherType.subjectOtherType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuedToIdentifier, issuedToName, subjectOtherType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubjectOtherType {\n");

    sb.append("    issuedToIdentifier: ").append(toIndentedString(issuedToIdentifier)).append("\n");
    sb.append("    issuedToName: ").append(toIndentedString(issuedToName)).append("\n");
    sb.append("    subjectOtherType: ").append(toIndentedString(subjectOtherType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
