/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SubjectNameType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")

public class SubjectNameType {
  /**
   * Gets or Sets nameType
   */
  @JsonAdapter(NameTypeEnum.Adapter.class)
  public enum NameTypeEnum {
    FN("fn"),
    PN("pn");

    private String value;

    NameTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static NameTypeEnum fromValue(String input) {
      for (NameTypeEnum b : NameTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<NameTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NameTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public NameTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return NameTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("nameType")
  private NameTypeEnum nameType = null;

  @SerializedName("tradeName")
  private String tradeName = null;

  public SubjectNameType() {
    this.nameType = NameTypeEnum.valueOf(this.getClass().getSimpleName());
  }
  public SubjectNameType nameType(NameTypeEnum nameType) {
    this.nameType = nameType;
    return this;
  }

   /**
   * Get nameType
   * @return nameType
  **/
  @Schema(required = true, description = "")
  public NameTypeEnum getNameType() {
    return nameType;
  }

  public void setNameType(NameTypeEnum nameType) {
    this.nameType = nameType;
  }

  public SubjectNameType tradeName(String tradeName) {
    this.tradeName = tradeName;
    return this;
  }

   /**
   * Get tradeName
   * @return tradeName
  **/
  @Schema(description = "")
  public String getTradeName() {
    return tradeName;
  }

  public void setTradeName(String tradeName) {
    this.tradeName = tradeName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubjectNameType subjectNameType = (SubjectNameType) o;
    return Objects.equals(this.nameType, subjectNameType.nameType) &&
        Objects.equals(this.tradeName, subjectNameType.tradeName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nameType, tradeName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubjectNameType {\n");

    sb.append("    nameType: ").append(toIndentedString(nameType)).append("\n");
    sb.append("    tradeName: ").append(toIndentedString(tradeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
