/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SubjectByType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class SubjectByType {
  @SerializedName("issuedByIdentifier")
  private SubjectIdentifierByType issuedByIdentifier = null;

  @SerializedName("issuedByName")
  private SubjectNameType issuedByName = null;

  public SubjectByType issuedByIdentifier(SubjectIdentifierByType issuedByIdentifier) {
    this.issuedByIdentifier = issuedByIdentifier;
    return this;
  }

   /**
   * Get issuedByIdentifier
   * @return issuedByIdentifier
  **/
  @Schema(required = true, description = "")
  public SubjectIdentifierByType getIssuedByIdentifier() {
    return issuedByIdentifier;
  }

  public void setIssuedByIdentifier(SubjectIdentifierByType issuedByIdentifier) {
    this.issuedByIdentifier = issuedByIdentifier;
  }

  public SubjectByType issuedByName(SubjectNameType issuedByName) {
    this.issuedByName = issuedByName;
    return this;
  }

   /**
   * Get issuedByName
   * @return issuedByName
  **/
  @Schema(required = true, description = "")
  public SubjectNameType getIssuedByName() {
    return issuedByName;
  }

  public void setIssuedByName(SubjectNameType issuedByName) {
    this.issuedByName = issuedByName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubjectByType subjectByType = (SubjectByType) o;
    return Objects.equals(this.issuedByIdentifier, subjectByType.issuedByIdentifier) &&
        Objects.equals(this.issuedByName, subjectByType.issuedByName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuedByIdentifier, issuedByName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubjectByType {\n");

    sb.append("    issuedByIdentifier: ").append(toIndentedString(issuedByIdentifier)).append("\n");
    sb.append("    issuedByName: ").append(toIndentedString(issuedByName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
