/*
 * KSeF
 * Krajowy Systemu e-Faktur
 *
 * OpenAPI spec version: 0.0.2
 * Contact: info.ksef@mf.gov.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.alapierre.ksef.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * TerminateSessionResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-19T16:15:43.054535+01:00[Europe/Warsaw]")
public class TerminateSessionResponse {
  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  @SerializedName("referenceNumber")
  private String referenceNumber = null;

  @SerializedName("processingCode")
  private Integer processingCode = null;

  @SerializedName("processingDescription")
  private String processingDescription = null;

  public TerminateSessionResponse timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public TerminateSessionResponse referenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

   /**
   * Get referenceNumber
   * @return referenceNumber
  **/
  @Schema(required = true, description = "")
  public String getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
  }

  public TerminateSessionResponse processingCode(Integer processingCode) {
    this.processingCode = processingCode;
    return this;
  }

   /**
   * Get processingCode
   * minimum: 100
   * maximum: 999
   * @return processingCode
  **/
  @Schema(required = true, description = "")
  public Integer getProcessingCode() {
    return processingCode;
  }

  public void setProcessingCode(Integer processingCode) {
    this.processingCode = processingCode;
  }

  public TerminateSessionResponse processingDescription(String processingDescription) {
    this.processingDescription = processingDescription;
    return this;
  }

   /**
   * Get processingDescription
   * @return processingDescription
  **/
  @Schema(required = true, description = "")
  public String getProcessingDescription() {
    return processingDescription;
  }

  public void setProcessingDescription(String processingDescription) {
    this.processingDescription = processingDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TerminateSessionResponse terminateSessionResponse = (TerminateSessionResponse) o;
    return Objects.equals(this.timestamp, terminateSessionResponse.timestamp) &&
        Objects.equals(this.referenceNumber, terminateSessionResponse.referenceNumber) &&
        Objects.equals(this.processingCode, terminateSessionResponse.processingCode) &&
        Objects.equals(this.processingDescription, terminateSessionResponse.processingDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, referenceNumber, processingCode, processingDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TerminateSessionResponse {\n");

    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("    processingCode: ").append(toIndentedString(processingCode)).append("\n");
    sb.append("    processingDescription: ").append(toIndentedString(processingDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
